### PR TITLE
60 add basic authentication

### PR DESCRIPTION
**Pull request by hokiegeek2**
This pull request addresses the following issues:

#60 
#345 
#337 (latest suggestions by @bradcray) 
#338 (in part)

### CODE REVIEW

**Comment by mhmerrill** [comment]
@hokiegeek2 is there a test we can run for authentication?

**Comment by hokiegeek2** [comment]
@mhmerrill yes, start arkouda_server with --authenticate. That will configure for basic authentication and you'll see the token show up in the server logging message. Go into client.connect and specify access_token=<token generated by server>

**Comment by mhmerrill** [comment]
@hokiegeek2 I noticed that `io_test.py` is commented out in the `pytest.ini` file, is this right? I merged what you had in your branch into master.

**Comment by hokiegeek2** [comment]
@mhmerrill argh, yeah, I did not rebase #406 prior to merge

**Pull request merged**
