### PR TITLE
Add a string argsort benchmark

### PR DESCRIPTION
**Pull request by ronawho**
Sample graphs at https://ronawho.github.io/ak-642/?startdate=2021/01/24&enddate=2021/01/27&graphs=argsortperformance,stringargsortperformance

### CODE REVIEW

**Review by reuster986 — APPROVED** [review]
I like this approach.

**Comment by reuster986** [comment]
@ronawho do you want to extend this approach to string groupby and string gather, and then I will withdraw my PR #640 ? Or were you thinking of a different path forward?

**Comment by ronawho** [comment]
Huh, sorry -- missed your comment from last week. Yeah, I'll extend this to groupby and gather.

**Comment by ronawho** [comment]
Closing in favor of https://github.com/mhmerrill/arkouda/pull/652

**Pull request closed without merging**
