### PR TITLE
348 replace python print statements with logging logger

### PR DESCRIPTION
**Pull request by hokiegeek2**

### CODE REVIEW

**Comment by mhmerrill** [comment]
@hokiegeek2 you are going to make the changes we talk about here.

- [ ] factory to make logger objects to bury stuff like verbose flag and getting env vars
- [ ] removing redundant code from different files

**Comment by mhmerrill** [comment]
@hokiegeek2 can i still use `ak.verbose` to turn on/off debug messages in the code?
like the idiom:
```python
ak.verbose = True
ak.ones(10)
ak.verbose = False
```

**Comment by hokiegeek2** [comment]
> @hokiegeek2 can i still use `ak.verbose` to turn on/off debug messages in the code?
> like the idiom:
> 
> ```python
> ak.verbose = True
> ak.ones(10)
> ak.verbose = False
> ```
> 
> maybe we could call it `ak.debug` instead?

@mhmerrill No, you would change the logging level to DEBUG, which would enable all debug messages to be written out. But, I can add helper methods named something like "enableVerbose/disableVerbose" and use that to set the logger handlers to DEBUG.

**Comment by mhmerrill** [comment]
> > @hokiegeek2 can i still use `ak.verbose` to turn on/off debug messages in the code?
> > like the idiom:
> > ```python
> > ak.verbose = True
> > ak.ones(10)
> > ak.verbose = False
> > ```
> > 
> > 
> > maybe we could call it `ak.debug` instead?
> 
> @mhmerrill No, you would change the logging level to DEBUG, which would enable all debug messages to be written out. But, I can add helper methods named something like "enableVerbose/disableVerbose" and use that to set the logger handlers to DEBUG. Please lemme know if that's cool.

it's cool

**Comment by hokiegeek2** [comment]
> > > @hokiegeek2 can i still use `ak.verbose` to turn on/off debug messages in the code?
> > > like the idiom:
> > > ```python
> > > ak.verbose = True
> > > ak.ones(10)
> > > ak.verbose = False
> > > ```
> > > 
> > > 
> > > maybe we could call it `ak.debug` instead?
> > 
> > 
> > @mhmerrill No, you would change the logging level to DEBUG, which would enable all debug messages to be written out. But, I can add helper methods named something like "enableVerbose/disableVerbose" and use that to set the logger handlers to DEBUG. Please lemme know if that's cool.
> 
> it's cool

Cool, I will...

image

**Comment by hokiegeek2** [comment]
@mhmerrill please take another look when you get a chance

**Review by mhmerrill — APPROVED** [review]
looks good

**Pull request merged**
