### PR TITLE
624 convert message format to json

### PR DESCRIPTION
**Pull request by hokiegeek2**
This PR encompasses the addition of client and server-side logic to implement JSON-formatted messages sent to/from the Arkouda server. The new and updated code is as follows:

1. Message classes that encapsulate Arkouda messages in Python (client) and Chapel (server) objects.
2. Logic to process JSON to/from Message objects 
3. Split messages from one space-delimited string or binary to a cmd field and an args field in a JSON object
4. Concept and corresponding enums for Message format (STRING or BINARY) and Message type (REGULAR, WARNING, or ERROR)
5. Refactored arkouda_server to (1) process the incoming message as having two parts: JSON string and, optionally a binary portion (e.g., array creation) and (2) cmd select statement that sends strings as opposed to binary objects to downstream Msg processors
6. Refactored Msg processors that now expect string objects w/ no decoding logic necessary

### CODE REVIEW

**Comment by reuster986** [comment]
@hokiegeek2 I like the approach here. Specifically, I like that the messages are objects in both the client and server, and this provides a path for further encapsulating and abstracting the details of messaging away from the logic of the commands.

One thing I would like to see before we merge this PR is all of the benchmarks run on our four test architectures, so that we preemptively catch any hidden performance regressions. For this reason, I might want to wait until PR #640 is merged, so that we have good string benchmarks to measure. @ronawho , once we finalize the string benchmarks and pull them into this PR, would you be able to build this PR and run benchmarks on the target architectures?

**Comment by hokiegeek2** [comment]
> @hokiegeek2 I like the approach here. Specifically, I like that the messages are objects in both the client and server, and this provides a path for further encapsulating and abstracting the details of messaging away from the logic of the commands.
> 
> One thing I would like to see before we merge this PR is all of the benchmarks run on our four test architectures, so that we preemptively catch any hidden performance regressions. For this reason, I might want to wait until PR #640 is merged, so that we have good string benchmarks to measure. @ronawho , once we finalize the string benchmarks and pull them into this PR, would you be able to build this PR and run benchmarks on the target architectures?

@reuster986 Cool, gotcha, makes sense.

**Comment by ronawho** [comment]
> @ronawho , once we finalize the string benchmarks and pull them into this PR, would you be able to build this PR and run benchmarks on the target architectures?

Yup, sounds good. FWIW while I'm happy to run benchmarks preemptively I also have no problem with just triaging the graphs the day after this goes in (I typically look at the graphs once a week anyways)

**Comment by reuster986** [comment]
@ronawho Thanks for keeping an eye on the graphs! Ordinarily, I would just merge the PR and look for regressions after the fact, but the code changes in this one are so pervasive that tracking down a regression might take a while, and I'd rather not have the pressure of fixing it in master. But I don't want to push us towards preemptive benchmarking for everything, because it's probably overkill in most cases.

**Comment by reuster986** [comment]
@hokiegeek2 if you rebase or pull master, then we can ask @ronawho to benchmark this PR to ensure no performance regressions.

**Comment by hokiegeek2** [comment]
@reuster986 Cool, on it now

**Comment by ronawho** [comment]
> @hokiegeek2 if you rebase or pull master, then we can ask @ronawho to benchmark this PR to ensure no performance regressions.

Ping me whenever you're ready. 

>  Thanks for keeping an eye on the graphs! Ordinarily, I would just merge the PR and look for regressions after the fact, but the code changes in this one are so pervasive that tracking down a regression might take a while, and I'd rather not have the pressure of fixing it in master. But I don't want to push us towards preemptive benchmarking for everything, because it's probably overkill in most cases.

We have a Chapel "playground" for testing branches before merging into dev, I wonder if something like that would be useful for arkouda too. It's basically another nightly performance configuration, but we could compare arkouda dev to an arkouda branch. We don't use our playground that regularly and typically just triage the graphs after the fact, but it can be really useful when making big changes like this.

**Comment by hokiegeek2** [comment]
Ready to roll

**Comment by hokiegeek2** [comment]
@reuster986 @ronawho I merged the upstream master and the CI workflow looks good, so we're ready for benchmark testing: 

image

**Comment by ronawho** [comment]
Running perf testing now

**Comment by ronawho** [comment]
I do not see any major regressions from this with a 16-node-cs-hdr run. There is a regression for the no-op test  (~13,500 no-ops/s -> ~7,500 no-ops/s) but I don't think is surprising since there's an extra memory allocation and string format added to every operation. I didn't see any noticeable impact on other benchmarks.

**Comment by hokiegeek2** [comment]
@ronawho Awesome! Thanks a bunch for running these benchmarks.

**Review by reuster986 — APPROVED** [review]

**Comment by reuster986** [comment]
@mhmerrill I think this is ready to go, and there are no performance regressions except for the expected no-op that @ronawho mentioned above. I'll let you pull the trigger on the merge, though, in case you have questions or concerns.

**Comment by ronawho** [comment]
Just confirming that I did not see any regression in nightly testing beyond the no-op one.

**Comment by hokiegeek2** [comment]
@ronawho Cool, thanks Elliot -> have a great weekend.

**Pull request merged**
