### PR TITLE
446 enable rethrowing of errors and passing in strings to errors

### PR DESCRIPTION
**Pull request by hokiegeek2**

### CODE REVIEW

**Comment by reuster986** [comment]
@hokiegeek2 I like what you've done here! I like the `ErrorWithContext` class, and I think that will be really helpful and could be a "one-stop shop" for arkouda errors thrown all the way up to the main server loop.

I see now what you mean about the difficulty of getting the class name. Given that, I think it is fine to leave out the class name, as long as we discipline ourselves to include a good error message whenever we throw one. For example, in `GenSymIO.chpl`, instead of throwing a `DatasetNotFoundError`, we could throw a `ErrorWithContext` with the message "dataset {name} not found in file {filename}", which I think would be more helpful than knowing the class name anyway. What do you think?

**Comment by hokiegeek2** [comment]
@reuster986 Cool, I think this will help us throw errors that are easier to investigate. I think throwing errors as ErrorWithContext with a detailed message is a good idea. The only caveat would be situations where we want to vary what we do in the error catch blocks depending upon the error conditions; in cases like these we may need child classes of ErrorWithContext.

**Comment by mhmerrill** [comment]
@hokiegeek2 I like this also.
We need to figure out how to incorporate this with the ServerErrorStrings.chpl.
I'd be willing to incorporate this but I think in light of this we need to rework all the other exceptions.
maybe we should do this in several increments? so we don't change ~27 files all at once?

**Comment by hokiegeek2** [comment]
@mhmerrill Yeah, increments is a good idea. Perhaps I can scope this to GenSymIO.chpl, end-to-end from Error through to message sent back to client. Once you and @reuster986 are good with that, we can roll out the design and implementation to the rest of Arkouda.

**Comment by mhmerrill** [comment]
@hokiegeek2 sounds good.

**Comment by hokiegeek2** [comment]
@mhmerrill @reuster986 Please take another look at this PR when y'all get a chance. I have pretty much all of the revamped error handling logic in place for GenSymIO (need to do one more check) and this PR now covers #316.

**Comment by mhmerrill** [comment]
> @mhmerrill @reuster986 Please take another look at this PR when y'all get a chance. I have pretty much all of the revamped error handling logic in place for GenSymIO (need to do one more check) and this PR now covers #316.

@hokiegeek2 are you ready to take this out of the draft state?

**Review by mhmerrill — COMMENTED** [review]
I think the changes look good, will wait on Bill's review also. Should we move this PR out of the draft state?

**Comment by hokiegeek2** [comment]
> I think the changes look good, will wait on Bill's review also. Should we move this PR out of the draft state?

Cool, yes, I recommend moving this PR out of draft state.

**Review by reuster986 — APPROVED** [review]
looks good!

**Comment by hokiegeek2** [comment]
@reuster986 @mhmerrill Thanks a bunch for reviewing!

**Pull request merged**
