### PR TITLE
703 define arkouda scalars to simplify method signatures

### PR DESCRIPTION
**Pull request by hokiegeek2**

### CODE REVIEW

**Review by mhmerrill — APPROVED** [review]
looks ok to me but I want @reuster986 to weigh in with his opinion.

**Review by reuster986 — CHANGES_REQUESTED** [review]
Yay! This is a huge improvement for both clarity and maintainability, so thank you!

Just one request: I and other users use `ak.bool` a fair amount, so can we please leave that as an alias to `np.bool` for backwards compatibility?

**Comment by hokiegeek2** [comment]
> Yay! This is a huge improvement for both clarity and maintainability, so thank you!
> 
> Just one request: I and other users use `ak.bool` a fair amount, so can we please leave that as an alias to `np.bool` for backwards compatibility?

Okay, I will make that change

**Comment by hokiegeek2** [comment]
@reuster986 requested changes made, please review
@mhmerrill I added a couple of dtypes unit tests

**Review by reuster986 — APPROVED** [review]
looks great!

**Pull request merged**
