### PR TITLE
added --ccflags="-Wno-incompatible-pointer-types" to makefile

### PR DESCRIPTION
**Pull request by mhmerrill**
incompatible-pointer-type warning started showing up again with HDF5 on our IB cluster so I added it back to the makefile.

### CODE REVIEW

**Comment by bradcray** [comment]
Bummer!  Want to add a comment to the line adding the flag so that next time we remember why it was added?  (though I suppose we could also look back at this PR now).  I'd be curious if you could post an excerpt of what the error message looks like.  I'm guessing that it's similar to the following longstanding issue on the Chapel repo: https://github.com/chapel-lang/chapel/issues/7983

**Comment by mhmerrill** [comment]
> Bummer! Want to add a comment to the line adding the flag so that next time we remember why it was added? (though I suppose we could also look back at this PR now). I'd be curious if you could post an excerpt of what the error message looks like. I'm guessing that it's similar to the following longstanding issue on the Chapel repo: [chapel-lang/chapel#7983](https://github.com/chapel-lang/chapel/issues/7983)

Yes this is what the warning looks like.

**Comment by ronawho** [comment]
The warning shows up in the Travis runs too -- https://travis-ci.com/mhmerrill/arkouda/builds/136442838

If you want to do this for gnu only you can do something like:

```make
TARGET_COMP = $(shell $(CHPL_HOME)/util/chplenv/chpl_compiler.py --target 2>/dev/null)
ifneq (, $(findstring gnu,$(TARGET_COMP)))
CHPL_FLAGS += --ccflags="-Wno-incompatible-pointer-types"
endif
```

**Comment by ronawho** [comment]
Just FYI that we made a similar change upstream in https://github.com/chapel-lang/chapel/pull/14446

Also fyi that this will fail on non gnu/clang compilers (I use the intel backend semi-frequently, but this may not be an important use-case for you)

**Pull request merged**
